### ISSUE TITLE
Cleaning up `design_update`

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#107]
Clean up design update branch with only working elements i.e. remove structs and functions that have not been tested, or still in dev. Work in progress could be moved to new branches, or kept in local branches, or removed entirely.

Make issues out of things are removed, eg. poststrafity.jl etc, so everyone remembers. add them to a milestone, and label them nicely. 

#98 is a subtask of this.

**Comment by ayushpatnaikgit** [comment]
I think this has been solved by multiple PRs, primarily #114 and #98
