### ISSUE TITLE
Need example for `mean(::Bool; x::Symbol, design::StratifiedSample)`

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#109]
Please add an example for the function in its docstrings.

**Comment by smishr** [comment]
This is to return strata means, since that is also interesting to analyse in many cases.

**Comment by iuliadmtru** [comment]
Why doesn't the first parameter have a name? Does there need to be a parameter if it's not used in the function body?

**Comment by iuliadmtru** [comment]
It might be better to remove this method for now.

**Comment by smishr** [comment]
@sayantikaSSG did you test the current state of the function?

**Comment by sayantikaSSG** [comment]
@smishr no I am not doing testing anymore

**Comment by smishr** [comment]
> @smishr no I am not doing testing anymore

sure, but did u "test" the current state of the function working as expected with `Stratified`

**Comment by sayantikaSSG** [comment]
Yes, it is working as expected.

**Comment by iuliadmtru** [comment]
This was removed with #117.
