### ISSUE TITLE
Forgotten `@show`s in constructor bodies

### ISSUE THREAD

**Issue by iuliadmtru** [xKDR/Survey.jl#111]
There are some `@show` macros in the constructor body for `SimpleRandomSample` and `StratifiedSample`.

**Comment by smishr** [comment]
i think the intent is to show the user the values(s) that caused the error message. So instead of show, should just have it in print statement?? I left it with @show because the printing is much neater.

**Comment by iuliadmtru** [comment]
I don't think the user needs to see the values. The error message is enough.

**Comment by iuliadmtru** [comment]
Solved by #116.
