### ISSUE TITLE
Test `show` method for survey design types

### ISSUE THREAD

**Issue by iuliadmtru** [xKDR/Survey.jl#120]
This method has 0 code coverage. It can be easily tested.

**Comment by ayushpatnaikgit** [comment]
How do you plan to test it?

**Comment by smishr** [comment]
Since we havent fully decided on the D.S. for survey designs, testing their show methods low priority.

**Comment by smishr** [comment]
wont be worked on right now, will reopen issue later

**Comment by iuliadmtru** [comment]
I added tests in #175.
