### ISSUE TITLE
General survey design

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#129]
How about the following design for the general `SurveyDesign`:

1. Every sample is a multistage stratified sample.  
2. If no strata are passed, it means there is 1 stratum, that contains everything.  
3. If no clusters are passed, it means observation is a cluster. 

For example, if you have a simple random sample, is a multistage sample where there is 1 stratum and every observation is a cluster.  

All the formulae will be for multistage stratified sample.

**Comment by smishr** [comment]
Im not sure the approximations for mean and variance would work out this way. You may be correct, but it should be checked beforehand. Current attempt at SurveyDesign follows similar philosophy as R, that is, tries to infer whether given inputs/data is SRS or Stratified.

**Comment by smishr** [comment]
"In the single-stage approximation the PSUs are treated as strata and the second-stage sampling units are treated as PSUs."

Rereading through Chap3 of Lumley

**Comment by smishr** [comment]
I am attempting to make a structure for cluster sampling, which accommodates multiple stages

**Comment by smishr** [comment]
I have been going through R `svydesign.default` function for the below 2-stage cluster sample command:
```R
dclus2<-svydesign(id=~dnum+snum, fpc=~fpc1+fpc2, data=apiclus2)
```

**Comment by ayushpatnaikgit** [comment]
I am making a bare minimum multistage survey design.
