### ISSUE TITLE
Jacknife for `SurveyDesign` variance estimation with `mean` `total` and `quantile` or any arbitrary function

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#137]
To implement Jacknife technique for survey sampling designs. To integrate with existing data structures and functions

**Comment by smishr** [comment]
Draft #135 implements some of the above

**Comment by smishr** [comment]
First try with mentioned three functions. Add tests for them.
Then try with arbitrary functions not defined in `Survey.jl` like `median` etc.

**Comment by smishr** [comment]
Look into encapsulating the jacknife function inside `mean`/`total` for `OneStageClusterSample`, as a keyword option. eg method = "jackknife" or method = "bootstrap".

**Comment by sayantikaSSG** [comment]
I am trying to incorporate the jackknife function in mean.jl and total.jl

**Comment by smishr** [comment]
Also there are some software engineering kinks that need to be sorted, like `params` not working for all arbitrary functions; keyword argument passing inside `func`. 
In `bootstrap.jl`, by default wsum is used, and `weights` argument is hardcoded into `func` call.

**Comment by smishr** [comment]
Type of new function could be `mean(x::Symbol, design::OneStageClusterSample, method::Jackknife)`

**Comment by smishr** [comment]
@sayantikaSSG task is to make Jackknife work with `SurveyDesign` in `singledesign` branch.

**Comment by smishr** [comment]
closed by #260
