### ISSUE TITLE
General `ratio` estimation for `SurveyDesign`

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#156]
TODO:
- `ratio` method that returns survey ratio of two columns. analogoues to `svyratio` command in R
- Firstly focus on point estimate only, later look at variance
- Look into [svyratio.survey.design](https://github.com/cran/survey/blob/master/R/survey.R) in R survey , I think line 755 is the main caluclation for svyratio
-

**Comment by sayantikaSSG** [comment]
The ratio method is added for survey ratio of two columns.
The Standard error is calculated using Jackknife method for simplicity.
Please refer to #158 pull request.

**Comment by ayushpatnaikgit** [comment]
> The ratio method is added for survey ratio of two columns. The Standard error is calculated using Jackknife method for simplicity. Please refer to #158 pull request.

This only for OneStageClusterSample.

**Comment by smishr** [comment]
@sayantikaSSG @ayushpatnaikgit should we try to do this in next few days?

**Comment by smishr** [comment]
#181 will update `ratio` method with `bootstrap` to calculate variance estimate

**Comment by smishr** [comment]
#187 added above feature into dev branch

**Comment by ayushpatnaikgit** [comment]
#181 will be merged, so let's close this.
