### ISSUE TITLE
`quantile` function

### ISSUE THREAD

**Issue by iuliadmtru** [xKDR/Survey.jl#171]
Is there a reason for this @smishr @ayushpatnaikgit? This happens in the `singledesign` branch. In the `main` branch, there used to be two different methods for `SimpleRandomSample` and `StratifiedSample`. Now that is not necessary, but there are two methods that are exactly the same. Can we delete one of them?

**Comment by smishr** [comment]
entire quantile file has to be rewritten i think. when that is done will remove both methods and add new.

**Comment by smishr** [comment]
Will be fixed with #172

**Comment by smishr** [comment]
New function was added by #183 using bootstrap for variance. This issue will be closed when #181 is merged into main
