### ISSUE TITLE
Failing tests in PR #247

### ISSUE THREAD

**Issue by itsdebartha** [xKDR/Survey.jl#248]
```Using RData``` in ```src/Survey.jl``` and ```test/runtests.jl``` causes tests to fail without including the dependencies in ```Project.toml```

Suggested fix:
Add ```RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"``` under `[deps]` inside ```Project.toml```

**Comment by ayushpatnaikgit** [comment]
Can you hyperlink the lines?

**Comment by smishr** [comment]
im udpating this in the PR #247
