### ISSUE TITLE
Rename `data` to `load_data` and improve it

### ISSUE THREAD

**Issue by greimel** [xKDR/Survey.jl#27]
... to avoid name clash with AlgebraOfGraphics.

Also, you could return a named tuple and encourage the user to use

```julia
(; apistrat) = dataset(api)
```

to avoid cluttering the namespace.

**Comment by ayushpatnaikgit** [comment]
Thanks, @greimel 

Perhaps `load_dataset(api)` ?

What do you think?
@harsharora21 @chiraganand @iuliadmtru 

While we want to keep the API similar to `survey`, I think calling the function `data` can't work out.

**Comment by iuliadmtru** [comment]
> Also, you could return a named tuple and encourage the user to use
> 
> ```julia
> (; apistrat) = dataset(api)
> ```
> 
> to avoid cluttering the namespace.

I agree with this, it is much cleaner and I think it makes more sense to have `data(api)` as an r value instead of having it define some global datasets.

**Comment by iuliadmtru** [comment]
> Perhaps `load_dataset(api)` ?

Maybe `load_data(api)`? Since `api` contains actually 5 datasets (`apiclus1`, `apiclus2`, `apistrat`, `apipop` and `apisrs`) it would make more sense to call it `load_datasets(api)` in this case. But it would be better to have a more general name so I prefer `load_data`.

**Comment by chiraganand** [comment]
IMHO, `load_data()` is concise yet descriptive. It follows the general "function names should be verbs" methodology which makes it more clear to the end user of the function's intentions.
