### ISSUE TITLE
Add frequency weights to `design.variables`

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#28]
Since many functions require frequency weights, we can store it in `design.variables` rather than having each function derive it from `probs`. 

Instead of `probs`, perhaps, we should call it `probability_weights_reserved`? Similarly, `frequency_weights_reserved`.

The reason we're only storing probability weights is that we didn't anticipate so many Julia functions to use frequency weights. I believe the `survey` package in R only store probability weights, and most R functions use probability weights. 

Note, we want the information about weights to be in the same data frame and not make it a property of `svydesign` because of performance reasons. `combine` function in `DataFrames` works a lot faster.

**Comment by iuliadmtru** [comment]
I fixed this with PR #32, although the discussion should remain open regarding the names of the fields.

**Comment by ayushpatnaikgit** [comment]
I will discuss this with @chiraganand on phone.
