### ISSUE TITLE
apiclus2 weights

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#291]
" The sampling weights in apiclus1 are incorrect (the weight should be 757/15) but are as obtained from UCLA. "
https://r-survey.r-forge.r-project.org/survey/html/api.html

I am uncertain if it's the case with apiclus2 as well. How can we check?

**Comment by smishr** [comment]
Look in R documentation of `api`. That is where I found that apiclus1 should be 757/15. afaik apiclus2 weights were correct? But we havent tested Survey.jl with two stage cluster samples like `apiclus2` much yet, so im not sure if it is an algorithm bug or issue with dataset.

**Comment by smishr** [comment]
we have sorted out by removing correction for apiclus2 in `runtests.jl`
