### ISSUE TITLE
Julian design for the package

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#40]
At first, we should make the package work for simple random samples and then extend the functionality to other design types.  The current design of the package doesn't allow development to be done in that way. 

How about: 

```julia

abstract type SurveyDesign end
struct SimpleRandomSample <: SurveyDesign
       data::DataFrame
end
struct StratifiedSample <: SurveyDesign
       data::DataFrame
end
function plot(x::SurveyDesign)
plot(x.data)
# works on any child of SurveyDesign
end
function mean(variable, x::SimpleRandomSample)
# computes the mean of a variable from a simple random sample
end
```

Later, we can add:

```julia
function mean(variable, x::StratifiedSample)
# computes the mean of a variable from a stratified sample. 
end
```

There is pristine clarity on which functions work on which design types. 
If we want to keep the API similar to R, we should consider wrappers.

**Comment by iuliadmtru** [comment]
I opened a new branch addressing this issue: https://github.com/xKDR/Survey.jl/tree/design_update

**Comment by nalimilan** [comment]
FWIW, I'd say calling this type `AbstractSurveyDesign` would make sense, following the naming pattern used in Base and many packages.

**Comment by iuliadmtru** [comment]
I added a comment that's relevant to this discussion here: https://github.com/xKDR/Survey.jl/pull/41#issuecomment-1225505137

**Comment by nalimilan** [comment]
I had also posted a few ideas at https://github.com/xKDR/Survey.jl/issues/4.

**Comment by iuliadmtru** [comment]
I suggest closing this issue. We have implemented the API discussed here and there have been a lot of changes in the mean time (especially in the singledesign branch lately). This specific discussion about a more Julian design is not relevant anymore. I think we are still not adhering to Julia style standards, but we should have another discussion about that.
