### ISSUE TITLE
Code coverage needs to be improved

### ISSUE THREAD

**Issue by iuliadmtru** [xKDR/Survey.jl#64]
> **_DISCLAIMER:_**  The following is based on my personal opinion, not on some official information. Please argue with me if you disagree.

The `design_update` branch is not tested properly nor completely. I suggest a plan of action to improve code coverage and some guidelines for test-writing.

First of all, we need to differentiate between **unit tests** and **integration tests**. Since they are conceptually different (one of them is done in a white-box manner and the other in a black-box manner) they can be done in parallel, or by different people. Generally, unit testing should be done while developing.

**Unit testing**
Every implemented function needs to be tested for every functionality it provides, starting from the base up (i.e. from constructors to high-level functionality like plotting). This means:
1. Go through each file inside `src` in the order low level - high level

2. Inside `test/filename` write tests for each function from the file `src/filename` such that the following are checked: 
    - [ ] test main functionality

       Example: `@test nrow(svyby(:api00, :stype, srs, svymean)) == apisrs.stype |> unique |> size |> first`

    - [ ] test all `if-else` cases of the function
    - [ ] test errors (using [`@test_throws`](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test_throws))
    - [ ] test warnings if appropriate (using [`@test_warn`](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test_warn))
    
    The simplest function should have at least two tests: one for main functionality and one for error check.

3. Make sure `test/filename` is included in the `test/runtests.jl` file.

**Integration testing**
The overall package needs to behave as expected. We need to think about scenarios that we would use the package for and build tests according to our expectations. The tests should answer common sense questions and edge-case questions starting with "What should happen if ..." (e.g. _What should happen if I have an empty survey?_ or _What should happen if I have a strata specifier for a `SimpleRandomSample`?_ or _What should happen if I only have one data point (and the rest are `missing`)?_ or anything else that your mind can think of).

**General guidelines**
- It is NOT necessary to avoid hardcoding tests, sometimes it is even advised (as seen [here](http://blogs.perl.org/users/buddy_burden/2020/02/to-hardcode-or-not-to-hardcode-that-is-the-unit-test-ion.html), [here](https://softwareengineering.stackexchange.com/questions/126652/should-unit-test-expected-results-be-hardcoded), [here](https://www.quora.com/Is-it-acceptable-to-have-hard-code-on-unit-tests) or on any other online search I could find). What IS necessary is making sure that the tests are not dependent on the environment.
- The test files should be as clean as the source files: no lingering prints, shows or comments, clear code, no long lines etc.
- We should separate the unit tests from the integration tests. I suggest a structure like:
```
test/
    integration/
        integration1.jl
        integration2.jl
        ...
    unit/
        SurveyDesign.jl
        svyby.jl
        ...
    runtests.jl
```
... but with more descriptive file names inside the `integration` folder.

**Comment by ayushpatnaikgit** [comment]
Codecov is a 100% now.
