### ISSUE TITLE
Parsing of keywords in Survey Design

### ISSUE THREAD

**Issue by sayantikaSSG** [xKDR/Survey.jl#67]
The Survey design does not check whether the sum of probabilities is less or equal to 1. Even when the sum is more than one the design works and throws no error.
`   srs_w_p = SimpleRandomSample(apisrs, ignorefpc = false, weights = :fpc, probs = fill(0.3, size(apisrs_original, 1)))`
This chunk of code throws no error even though the sum of probability is more than 1.

**Comment by iuliadmtru** [comment]
There is a larger issue regarding this. The `if-else` statements inside the `SimpleRandomSample` constructor need to be corrected. And likely the ones for `StratifiedSample` as well.

**Comment by smishr** [comment]
I tried adding a few simple constraints if user provides incorrect/inconsistent keyword arguments, but it needs more systematic thought on the argument parsing if-else ladder.

**Comment by smishr** [comment]
I am working on this and similar issues I have encountered while testing and debugging

**Comment by smishr** [comment]
#94 and #95 improve the parsing of keywords and type checking. This creates a foundation on which future sampling schemes can be built.
