### ISSUE TITLE
Negative float as sampsize and popsize

### ISSUE THREAD

**Issue by sayantikaSSG** [xKDR/Survey.jl#75]
There is another issue in SurveyDesign.jl. If you write the following code, then the error message showing is not what it should be
`srs = SimpleRandomSample(apisrs, popsize = -2.8, ignorefpc = true)`
the error message is 

> either population size or frequency/probability weights must be specified

Also for this code 
`    srs = SimpleRandomSample(apisrs, sampsize = -2.8, ignorefpc = true)# the function is working up to line 55`
the function is working all the way up to the 55th line and then only shows that there is an error giving the following message:

> ERROR: InexactError: UInt64(-3.0)

My suggestion is we add some check that lets us proceed with the function only if the sampsize and popsize are non-negative integers.

**Comment by smishr** [comment]
Checks added to resolve above in #94 #95
