### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by iuliadmtru** [xKDR/Survey.jl#78]
The README currently shows examples using the old design. The values given in those examples are not even correct (we corrected them for the [new design](https://github.com/xKDR/Survey.jl/tree/design_update)). The old examples need to be replaced with new ones corresponding to the new design.

**Comment by smishr** [comment]
Yes. ideally the readme takes one or two great examples from the test/ code

**Comment by smishr** [comment]
I updated the intro of README
