### ISSUE TITLE
Domain estimation - SimpleRandomSample - svyby svymean doesnt use passed `weights` argument 

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#80]
In the line of svyby for SimpleRandomSample we pass `:weights`. But then never use it later in svymean. Remove if not required. Double check with the Cochran slides implemented from

`return combine(gdf, [formula, :weights] => ((a, b) -> func(a, design, b, params...)) => AsTable)`

**Comment by iuliadmtru** [comment]
We use the weights for `svytotal`. Since we use `svyby` for both `svytotal` and `svymean` (and other functions in the future) we need to either consider multiple dispatch, or pass all the parameters needed by all the functions inside `svyby`. The `params...` argument might be unnecessary though.

**Comment by smishr** [comment]
Okay. As discussed i am closing this issue

**Comment by iuliadmtru** [comment]
`svyby` is not used anymore. The functionality has been implemented as methods of `mean` and `total`.
