### ISSUE TITLE
Proportion and count estimation for `SimpleRandomSample` and `StratifiedSample`

### ISSUE THREAD

**Issue by smishr** [xKDR/Survey.jl#81]
In R `survey`, population proportions and population total estimation is done by passing a 'factor' (CategoricalArray) variable to `svymean` `svytotal` (see pg 21 Lumley textbook). 

Basic proportion and count estimation functionality was added to `SimpleRandomSample` and started for `StratifiedSample`, inside their respective svymean and svytotal functions to emulate functionality from R. This is currently done using an `if` statement

I am thinking that it would be neater and cleaner to have these features as multiple dispatch, instead of being caught by the `if`. Minor improvements in speed would also be there for very large datasets by using multiple dispatch.

**Comment by smishr** [comment]
#89 adds some of this functionality

**Comment by smishr** [comment]
#102 Adds some more features

**Comment by smishr** [comment]
Still need to add more testing in test/mean.jl and test/total.jl for CategoricalArray

**Comment by iuliadmtru** [comment]
Testing for `CategoricalArray` support is covered in issues #103 and #104.
