### ISSUE TITLE
Some branches need to be deleted

### ISSUE THREAD

**Issue by iuliadmtru** [xKDR/Survey.jl#88]
Branches like `hartley-rao-se` and `revert-*` need to be deleted.

**Comment by iuliadmtru** [comment]
I removed one of the `revert` branches, the one that was merged. The other `revert` branch was not merged ([`79-78-readme-needs-to-be-updated`](https://github.com/xKDR/Survey.jl/tree/revert-79-78-readme-needs-to-be-updated)) but I will remove it as well since we need to update the README file anyway. I will remove the `78-readme-needs-to-be-updated` branch as well, we can do a new PR when we update de README.

**Comment by iuliadmtru** [comment]
The [`hartley-rao-se`](https://github.com/xKDR/Survey.jl/tree/hartley–rao-se) branch is ahead of main by 12 commits. I took a look through them and they all look outdated. I think we can safely delete this branch, what do you think @ayushpatnaikgit?

**Comment by ayushpatnaikgit** [comment]
@iuliadmtru you can delete [hartley-rao-se](https://github.com/xKDR/Survey.jl/tree/hartley%E2%80%93rao-se) branch as well.

**Comment by smishr** [comment]
I am deleting `hartley-rao-se` branch and resolving this issue
