### ISSUE TITLE
Section or appendix in the documentation showing R code

### ISSUE THREAD

**Issue by ayushpatnaikgit** [xKDR/Survey.jl#97]
Examples should have references to equivalent R code. The references could be done by creating an appendix in the API reference, or there should be a separate section.

**Comment by smishr** [comment]
I think once we get some time, we should make a page with several real-world survey, with constructing the survey design object, finding the mean etc. Take inspiration from [Analyse Survey Data Free](https://github.com/ajdamico/asdfree). Or translate some of the R code here into Survey.jl
